version: '2'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fairy-app
    ports:
      - '8400:8400'
    expose:
      - 8400
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fairy_pos
      - SPRING_DATASOURCE_USERNAME=os
      - SPRING_DATASOURCE_PASSWORD=secret
  crdb:
    image: cockroachdb/cockroach:v23.1.13
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - ./docker/cockroach-data/crdb:/cockroach/cockroach-data
  mysql:
    container_name: fairy-mysql
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=os
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./docker/mysql/data:/bitnami/mysql/data
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/:ro
