server:
  port: 8400
  ssl:
    key-store-type: PKCS12
    key-store=: classpath:keystore/fairy.p12
    key-store-password: fairy2023
    key-alias: fairy
    enabled: true

spring:
  config:
    import:
      - auth.yml
      - domain.yml
      - persistence.yml
  mvc:
    static-path-pattern: /swagger*
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /api/swagger-ui
